site_name: UDE solving for General Relativity
theme:
  name: material  # Modern theme
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google  # Supports Google, NumPy, reStructuredText
nav:
  - Home: index.md
  - API Reference: api.md
